# Generated by Django 2.2.11 on 2020-03-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20200318_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
