# Generated by Django 2.2.11 on 2020-03-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='accepted',
        ),
    ]
