# Generated by Django 2.2.11 on 2020-03-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20200318_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='was_forefit',
            new_name='was_forfeit',
        ),
    ]
