# Generated by Django 2.2.11 on 2020-03-30 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20200322_2001'),
        ('matches', '0008_match_rank_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='challenger',
        ),
        migrations.RemoveField(
            model_name='match',
            name='defender',
        ),
        migrations.RemoveField(
            model_name='match',
            name='forfeit_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='rank_applied',
        ),
        migrations.RemoveField(
            model_name='match',
            name='scheduled',
        ),
        migrations.CreateModel(
            name='LadderMatch',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matches.Match')),
                ('rank_applied', models.BooleanField(default=False)),
                ('scheduled', models.DateTimeField(blank=True, null=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger_matches', to='teams.Team')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender_matches', to='teams.Team')),
                ('forfeit_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forfeit_matches', to='teams.Team')),
            ],
            bases=('matches.match',),
        ),
    ]
