# Generated by Django 2.2.11 on 2020-03-31 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_auto_20200330_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laddermatch',
            old_name='rank_applied',
            new_name='ranking_applied',
        ),
    ]
