# Generated by Django 2.2.11 on 2020-03-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200318_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.PositiveSmallIntegerField(default=9999),
        ),
    ]
