# Generated by Django 2.2.11 on 2020-03-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='rank',
            new_name='ladder_rank',
        ),
    ]
