# Generated by Django 2.2.11 on 2020-03-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20200322_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['ladder_rank']},
        ),
    ]
