# Generated by Django 2.2.11 on 2020-03-31 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20200322_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.RemoveField(
            model_name='team',
            name='ladder_rank',
        ),
    ]
