# Generated by Django 2.2.11 on 2020-03-31 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20200331_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['rank__position']},
        ),
    ]
