# Generated by Django 2.2.11 on 2020-03-31 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20200331_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['ranking__position']},
        ),
    ]
