# Generated by Django 2.2.11 on 2020-03-31 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20200331_0256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['ladder_ranking__position']},
        ),
    ]
