# Generated by Django 2.2.11 on 2020-03-18 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rematch_wait', models.DurationField(default=datetime.timedelta(days=7))),
                ('challenge_response_time', models.DurationField(default=datetime.timedelta(days=3))),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
            ],
        ),
    ]
