# Generated by Django 2.2.11 on 2020-03-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ladder',
            old_name='challenge_response_time',
            new_name='result_deadline',
        ),
    ]
