# Generated by Django 2.2.11 on 2020-03-31 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0003_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='ladder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladders.Ladder'),
        ),
    ]
