# Generated by Django 2.2.11 on 2020-03-31 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20200331_0256'),
        ('ladders', '0005_auto_20200331_0253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranking',
            new_name='LadderRanking',
        ),
    ]
