# Generated by Django 2.2.11 on 2020-03-31 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0006_auto_20200331_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladderranking',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ladder_ranking', to='teams.Team'),
        ),
    ]
