# Generated by Django 2.2.11 on 2020-03-31 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladders', '0007_auto_20200331_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladderranking',
            name='ladder',
        ),
    ]
