# Generated by Django 2.2.11 on 2020-03-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='title',
            new_name='name',
        ),
    ]
