# Generated by Django 2.2.11 on 2020-03-30 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0002_auto_20200318_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='captains',
            field=models.ManyToManyField(related_name='captain_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
